import Anthropic from '@anthropic-ai/sdk';
import { zodOutputFormat } from '@anthropic-ai/sdk/helpers/zod';
import {
  RawOnboardingTurnSchema,
  normalizeRawTurn,
  toClaudeMessages,
  assertValidReplyText,
  type OnboardingTurnResult,
  type ChatMessage,
} from './extraction';
import { ONBOARDING_SCRIPT, type OnboardingScriptStep } from './script';

const MODEL = 'claude-sonnet-5';

const TURN_FAILED_MESSAGE = 'No se pudo continuar la conversación, intenta de nuevo.';

// The SDK's default request timeout is 10 minutes, which left users staring at a
// disabled "Enviar" button with no feedback during a real network hiccup. Fail
// fast with at most 1 SDK-level retry so a hung call surfaces the existing
// "Reintentar" flow within ~1 minute instead of up to 10.
const CLAUDE_TIMEOUT_MS = 30_000;
const CLAUDE_MAX_RETRIES = 1;

export async function runOnboardingTurn(
  transcript: ChatMessage[],
  script: OnboardingScriptStep[] = ONBOARDING_SCRIPT,
  client: Anthropic = new Anthropic()
): Promise<OnboardingTurnResult> {
  let response;
  try {
    response = await client.messages.parse(
      {
        model: MODEL,
        max_tokens: 4096,
        system: buildSystemPrompt(script),
        messages: toClaudeMessages(transcript),
        output_config: { format: zodOutputFormat(RawOnboardingTurnSchema) },
      },
      { timeout: CLAUDE_TIMEOUT_MS, maxRetries: CLAUDE_MAX_RETRIES }
    );
  } catch {
    // Truncation, schema-validation failures and network/API errors all land here.
    // Surface a stable, user-facing message instead of raw SDK/Zod internals.
    throw new Error(TURN_FAILED_MESSAGE);
  }

  if (!response.parsed_output) {
    throw new Error('Claude no devolvió una respuesta estructurada válida');
  }

  const result = normalizeRawTurn(response.parsed_output);
  assertValidReplyText(result.assistantReply, TURN_FAILED_MESSAGE);
  return result;
}

// The three narrative fields (currentEnergySummary, blockingPattern, futureVision) are
// generated by a dedicated, separately-timed call — see synthesis.ts — once the script
// below is complete, so they're deliberately excluded from this turn's "done" condition.
const REQUIRED_FIELDS = [
  'name',
  'currentAge',
  'futureSelfAge',
  'focusArea',
  'tone',
  'values',
  'goals',
] as const;

function buildSystemPrompt(script: OnboardingScriptStep[]): string {
  const steps = script.map((s, i) => `${i + 1}. ${s.instruction}`).join('\n');
  return `Eres un guía cálido que ayuda a alguien a prepararse para recibir mensajes diarios de su "yo futuro", a través de una conversación profunda y progresiva en español. Sigue este guion en orden, una pregunta a la vez, dejando que cada respuesta informe la siguiente:
${steps}

No preguntes por el tono que prefiere para los mensajes (motivador, exigente, tierno o directo) — infiérelo tú del registro emocional de toda la conversación.

Tampoco preguntes directamente por "values" ni "goals" — infiérelos tú también: "values" de cómo describe la versión de sí misma que quiere ser, y "goals" de su visión a 6 meses, 1 año y a largo plazo.

Cuando ya hayas recorrido el guion completo, ciérralo con calidez y agradécele por compartir — no intentes sintetizar ni resumir nada todavía, eso ocurre en un paso aparte.

En cada turno, responde con un JSON que tenga: "assistantReply" (un mensaje breve, cálido y natural para continuar la conversación, o para cerrarla cálidamente una vez cubierto el guion), "extracted" (todos los datos que puedas inferir con confianza de TODA la conversación hasta ahora, usando null en lo que aún no sepas con certeza), y "done" (true solo cuando estos campos ya tengan un valor no nulo en "extracted": ${REQUIRED_FIELDS.join(', ')}).`;
}
