-- One short daily insight per user per day, generated by the cron alongside the daily
-- message and tasks, and shown on the dashboard (not in the email).
-- insight_date is the user's LOCAL calendar date (per profiles.timezone), computed by the
-- app, same as daily_tasks.task_date.
-- The unique constraint makes generation idempotent: a cron retry for the same user and
-- day cannot insert a second insight. Its index also serves the dashboard's "most recent
-- insight for this user" read.
create table daily_insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  insight_date date not null,
  content text not null check (length(btrim(content)) > 0),
  model_used text not null,
  created_at timestamptz not null default now(),
  unique (user_id, insight_date)
);

alter table daily_insights enable row level security;

-- Users can only read their own insights: no insert, update or delete.
-- Insights are created solely by the cron using the service_role key, which bypasses RLS.
create policy "daily_insights_select_own" on daily_insights for select using (auth.uid() = user_id);

-- Table privileges (daily_tasks needed these added afterwards, in 0006: without them even
-- the service_role key failed with "permission denied"). Start from nothing for the
-- client roles, then give authenticated read-only access, matching the policy above.
revoke all on public.daily_insights from anon, authenticated;
grant select on public.daily_insights to authenticated;
grant all on public.daily_insights to service_role;
